### PR TITLE
Upgrade to .NET 8

### PR DESCRIPTION
**Pull request by matfricker**
### Main reason for pull request is to update project to .NET 8.

Other changes listed below:

- Updating nuget packages.
- Created a Test project with basic tests.
- Created an Implementation / Example project.
- One of the bigger changes is adding an HttpClientFactory to the SharpTrooperCore constructor, to move away from HttpWebRequest.
- Also made endpoints asynchronous.

### CODE REVIEW

**Comment by matfricker** [comment]
Just realised I never updated the readme in this request.

**Review by olcay — APPROVED** [review]
That was an old repo. You made my day @matfricker 

Thank you for your nice work.

**Comment by olcay** [comment]
Now, I remember your previous PR. I wrote the same comment there as well.

This repo stays alive, thanks to you @matfricker

**Comment by matfricker** [comment]
> Now, I remember your previous PR. I wrote the same comment there as well.
> 
> 
> 
> This repo stays alive, thanks to you @matfricker 

No problem, fun little task. Will update readme soon. 👍🏻

**Comment by olcay** [comment]
I updated readme but feel free to do any changes. It is more like your repo now.

**Pull request merged**
